# config to get 90.23% sparse ResNet50 on ImageNet. Modify this file to get other sparse models.
# Architecture
arch: resnet32

# ===== Dataset ===== #
data: data/
set: CIFAR100
name: resnet32_c100_STR

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr
warmup_length: 0

# ===== Network training config ===== #
epochs: 300
weight_decay: 0.001 # Change this according to reported numbers in appendix
momentum: 0.9
batch_size: 256
label_smoothing: 0

# ===== Sparsity =========== #
conv_type: STRConv
bn_type: LearnedBatchNorm
init: kaiming_normal
mode: fan_in
nonlinearity: relu
sparse_function: sigmoid
sInit_value: -3200 # Change this according to reported numbers in appendix

# ===== Hardware setup ===== #
workers: 8
